let std = import std

()
    let fail_exists = (): std.string
        //Fail doesn't return anything. It just halts the program.
        fail()
